const TODOS_FILTER_ALL = `TODOS_FILTER_ALL`;
const TODOS_FILTER_COMPLETED = `TODOS_FILTER_COMPLETED`;
const TODOS_FILTER_UNCOMPLETED = `TODOS_FILTER_UNCOMPLETED`;

const TODOS_FILTER = [
  { title: `All`, value: TODOS_FILTER_ALL },
  { title: `Completed`, value: TODOS_FILTER_COMPLETED },
  { title: `Uncompleted`, value: TODOS_FILTER_UNCOMPLETED },
];

export {
  TODOS_FILTER_ALL,
  TODOS_FILTER_COMPLETED,
  TODOS_FILTER_UNCOMPLETED,
  TODOS_FILTER,
};
